version: '2'

services:
  trackstat:
    container_name: ${COMPOSE_PROJECT_NAME}-${TRACKSTAT_CONTAINER_NAME}
    image: ${COMPOSE_IMAGE_NAME}
    build: .
    depends_on:
      - postgres
    network_mode: "service:postgres"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://localhost:5432/testdb

  postgres:
    image: postgres:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-${POSTGRES_CONTAINER_NAME}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    volumes:
      - "$PWD/database:/var/lib/postgresql/data"
    ports:
      - "80:8080" # tomcat port

