server:
  error:
    whitelabel:
      enabled: false
  port: ${TRACKSTAT_PORT:8080}
spring:
  jackson:
    default-property-inclusion: non_null
  # There is problem with verification of postgres's CLOB by Hibernate. You can
  # to find more information here:
  # https://vkuzel.com/spring-boot-jpa-hibernate-atomikos-postgresql-exception
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    platform: postgres
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/testdb}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
